version: '3'
services:
  web:
    image: keymetrics/pm2:latest-stretch
    restart: always
    container_name: blog
    environment:
      PORT: 9000
    ports:
      - 9000:9000
    volumes:
      - '.:/data'
    working_dir: /data/server
    command: pm2-runtime start ecosystem.config.js
